// <auto-generated />
using System;
using AccesoDatos.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccesoDatos.Migrations
{
    [DbContext(typeof(ObligatorioContexto))]
    [Migration("20251018193217_EntidadesBaseCompletas")]
    partial class EntidadesBaseCompletas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Estructura.Entidades.Equipo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("Estructura.Entidades.Pago", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("metodoPago")
                        .HasColumnType("int");

                    b.Property<int>("tipoGastoid")
                        .HasColumnType("int");

                    b.Property<int>("usuarioid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("tipoGastoid");

                    b.HasIndex("usuarioid");

                    b.ToTable("Pagos");

                    b.HasDiscriminator().HasValue("Pago");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Estructura.Entidades.TipoGasto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TiposDeGasto");
                });

            modelBuilder.Entity("Estructura.Entidades.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("equipoid")
                        .HasColumnType("int");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rol")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("equipoid");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Estructura.Entidades.PagoRecurrente", b =>
                {
                    b.HasBaseType("Estructura.Entidades.Pago");

                    b.Property<DateTime>("fechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("montoMensual")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("PagoRecurrente");
                });

            modelBuilder.Entity("Estructura.Entidades.PagoUnico", b =>
                {
                    b.HasBaseType("Estructura.Entidades.Pago");

                    b.Property<DateTime>("fechaPago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("numRecibo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("PagoUnico");
                });

            modelBuilder.Entity("Estructura.Entidades.Pago", b =>
                {
                    b.HasOne("Estructura.Entidades.TipoGasto", "tipoGasto")
                        .WithMany()
                        .HasForeignKey("tipoGastoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estructura.Entidades.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tipoGasto");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("Estructura.Entidades.Usuario", b =>
                {
                    b.HasOne("Estructura.Entidades.Equipo", "equipo")
                        .WithMany()
                        .HasForeignKey("equipoid");

                    b.Navigation("equipo");
                });
#pragma warning restore 612, 618
        }
    }
}
